# based on https://github.com/esphome/firmware/blob/main/bluetooth-proxy/esp32-generic.yaml
esphome:
  name: sliding-door-ctl
  friendly_name: Sliding Door
  name_add_mac_suffix: false
  project:
    name: esphome.bluetooth-proxy
    version: "1.0"
  comment: "https://github.com/kfix/esphome-autoslide-controller"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  ## dump out more stuff
  #level: VERBOSE

<<: !include network.yaml

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
   active: true

### refer to "Modbus RTU protocol for ATM door system V2" documentataion
### http://autoslide.com/wp-content/uploads/2022/11/AutoSlide-ATM2-Modbus-Protocols.pdf
uart:
  id: mod_bus
  tx_pin: 21
  rx_pin: 22
  baud_rate: 9600
  stop_bits: 1
  data_bits: 8
  parity: NONE

modbus:
  # "DE"/"RE"
  flow_control_pin: 23
  send_wait_time: 700ms
  id: mod_bus_autoslide

modbus_controller:
  - id: autoslide
    ## the Modbus device addr
    address: 0x1
    modbus_id: mod_bus_autoslide
    command_throttle: 200ms
    setup_priority: -10
    update_interval: 5s

text_sensor:
  - platform: modbus_controller
    modbus_controller_id: autoslide
    id: status
    name: "opener status"
    address: 0x0004
    force_new_range: true
    register_type: holding
    filters:
      - map:
        - 0000 -> closed
        - 0001 -> closed & locked
        - 0002 -> open
    raw_encode: HEXBYTES

select:
  - platform: modbus_controller
    modbus_controller_id: autoslide
    id: mode
    name: "select mode"
    address: 0x0002
    force_new_range: true
    value_type: U_WORD
    optionsmap:
      "Auto": 0
      "Stacker": 1
      "Lock": 2
      "Pet": 3

output:
  - platform: modbus_controller
    modbus_controller_id: autoslide
    id: indoor_button
    address: 0x1
    value_type: U_WORD
    register_type: holding
    multiply: 1
  - platform: modbus_controller
    modbus_controller_id: autoslide
    id: pet_sensor
    address: 0x1
    value_type: U_WORD
    register_type: holding
    multiply: 3

button:
  - platform: output
    name: "door button"
    output: "indoor_button"
    duration: 500ms
  - platform: output
    name: "pet sensor"
    output: "pet_sensor"
    duration: 500ms

